### ISSUE TITLE
[jruby] gem install won't upgrade to the latest version

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab2-addons#4]
Not sure if I should open this issue here or over at openhab-jruby.

It seems that the inline bundler `gemfile` doesn't upgrade existing gems. I'm stuck at 4.12.0 even after several restarts. It only installs gems if they don't already exist.

**Comment by jimtng** [comment]
@boc-tothefuture we might want to fix this before the inclusion into openhab-addons

**Comment by boc-tothefuture** [comment]
Ok - I will take a look at it tomorrow morning.

**Comment by boc-tothefuture** [comment]
Hmm.  The bundler solution may not work.  Bundler won't upgrade the gem because the downloaded gem meets the specifications provided and I don't see a way to do an inline bundler update.

**Comment by jimtng** [comment]
The latest iteration with Gem.install did upgrade the gem version, but it broke the script reloading again.

**Comment by boc-tothefuture** [comment]
Ugh.  Do you get an exception?  I catch throwable now - not sure how it can kill the thread.

**Comment by boc-tothefuture** [comment]
I also don't get it locally when testing against 3.2M3

**Comment by jimtng** [comment]
No exceptions, no errors that I can see, it just won't reload.

I have narrowed down the cause to the new [ScriptLibraryWatcher](https://github.com/openhab/openhab-core/blob/main/bundles/org.openhab.core.automation.module.script.rulesupport/src/main/java/org/openhab/core/automation/module/script/rulesupport/internal/loader/ScriptLibraryWatcher.java), specifically its latest change to remove "javascript" in the path, resulting in this class now operating on everything in conf/automation/lib/.

I reverted the commit by just changing this line back to:
```
    public static final String LIB_PATH = String.join(File.separator, OpenHAB.getConfigFolder(), "automation", "lib",
            "javascript");
```
I then compiled the `org.openhab.core.automation.module.script.rulesupport-3.2.0-SNAPSHOT.jar` and inserted it into my 3.2m4 installation:
```
openhab> bundle:list -s | grep automation
161 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation
162 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.module.media
163 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.module.script
164 │ Active │  80 │ 3.2.0.202111080104    │ org.openhab.core.automation.module.script.rulesupport
165 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.rest
238 │ Active │  80 │ 3.2.0.202111071520    │ org.openhab.automation.jrubyscripting
```

This "fixed" the script reload.

I haven't yet figured out why our gem installer is affecting it. Perhaps something to do with temp files or anything that's going on during the gem installation process because it's dealing with the automation/lib directory too.

**Comment by jimtng** [comment]
Possible solution: move GEM_HOME out of `automation/lib`

I tested this by setting gem_home in jruby.cfg to `<OPENHAB_CONF>/scripts/lib/ruby/gem_home` and I can confirm that script reloading works with the standard 3.2m4 (not using my modified org.openhab.core.automation.module.script.rulesupport above).

```
openhab> bundle:list -s | grep automation
161 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation
162 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.module.media
163 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.module.script
164 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.module.script.rulesupport
165 │ Active │  80 │ 3.2.0.M4              │ org.openhab.core.automation.rest
238 │ Active │  80 │ 3.2.0.202111071520    │ org.openhab.automation.jrubyscripting
```

**Comment by boc-tothefuture** [comment]
If the new version is watching that entire dir for changes we don't want to put gems in there.

Does that scripts dir you reference exist by default?

**Comment by boc-tothefuture** [comment]
When you had the bundler version do you know where it was putting the gems?

**Comment by jimtng** [comment]
`<CONF>/scripts` exists by default (I think). 
The rest of the path from lib/... doesn't exist by default

**Comment by jimtng** [comment]
> When you had the bundler version do you know where it was putting the gems?

The bundler version also installs into GEM_HOME, and at the time it went into conf/automation/lib/ruby/gem_home too. I think the difference is because it just installs once when the gem isn't there, and after that it does nothing, that's why it appeared to be working.

**Comment by boc-tothefuture** [comment]
What do we think the best path forward is here?

Should we not have a default gem home?  Make the user set it explicitly or have a default and create the dirs to get there?

**Comment by jimtng** [comment]
We can set the default to scripts/lib/ruby/gem_home (got any better suggestions?) 
or scripts/ruby/gem_home ?

However, we should not auto create it. This gives the user an opportunity to specify a different path should it be desired, and they'll have to create it manually, so they really know what's going on.

**Comment by boc-tothefuture** [comment]
If we set it to by default to script/lib/ruby/gem_home wont it blow up if that directory doesn't exist?

I was proposing that no matter what directory they select (default or another directory) we ensure it exists.

**Comment by jimtng** [comment]
OK the middleground: only create it if they specified it in jruby.cfg, i.e. not when it's just the default.

We can also do a check for directory existence before doing gem install?

**Comment by jimtng** [comment]
I just want to avoid the binding creating the directory automatically when someone had just added the binding before they had a chance to configure it to point elsewhere.

**Comment by boc-tothefuture** [comment]
So, if they specify a gem it ensure the directory exists? That seems like a good path forward.

**Comment by jimtng** [comment]
> So, if they specify a gem it ensure the directory exists? That seems like a good path forward.

My idea was if they specified the gem_home in jruby.cfg but your idea is better, because there's no need to create the directory at all if they don't even specify any gems to be installed.

**Comment by boc-tothefuture** [comment]
Ok, pushed that update.

**Comment by jimtng** [comment]
Looks good. I'll close this issue.
