### ISSUE TITLE
[jruby] document putting gem_home outside conf/automation/lib

### ISSUE THREAD

**Issue by jimtng** [boc-tothefuture/openhab2-addons#7]
We should mention in the readme that people should avoid setting `GEM_HOME` inside `conf/automation/lib` directory.

Link for future reference: #4

**Comment by boc-tothefuture** [comment]
@jimtng can this be closed now?

**Comment by jimtng** [comment]
I suppose at this point putting GEM_HOME inside conf/automation/lib would still work, so it's not as important to avoid it, plus the doc already says that the default is in scripts. So Yes, we can close this.
